In [1]:
import pandas as pd
import numpy as np

import requests

In [4]:
response = requests.get("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [5]:
response

In [7]:
response.text

'PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked\n1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,,S\n2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38,1,0,PC 17599,71.2833,C85,C\n3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.925,,S\n4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1,C123,S\n5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.05,,S\n6,0,3,"Moran, Mr. James",male,,0,0,330877,8.4583,,Q\n7,0,1,"McCarthy, Mr. Timothy J",male,54,0,0,17463,51.8625,E46,S\n8,0,3,"Palsson, Master. Gosta Leonard",male,2,3,1,349909,21.075,,S\n9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27,0,2,347742,11.1333,,S\n10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14,1,0,237736,30.0708,,C\n11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4,1,1,PP 9549,16.7,G6,S\n12,1,1,"Bonnell, Miss. Elizabeth",female,58,0,0,113783,26.55,C103,S\n13,0,3,"Saundercock, Mr. William Henry",male,20,0,0,A/5. 2151,8.05,,S\n14,0,3,"Andersson, Mr. Anders Johan",male,39,1,5,347082,31.275,,S\n15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14,0,0,350406,7.8542,,S\n16,1,2,"Hewlett, Mrs. (Mary D Kingcome) ",female,55,0,0,248706,16,,S\n17,0,3,"Rice, Master. Eugene",male,2,4,1,382652,29.125,,Q\n18,1,2,"Williams, Mr. Charles Eugene",male,,0,0,244373,13,,S\n19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)",female,31,1,0,345763,18,,S\n20,1,3,"Masselmani, Mrs. Fatima",female,,0,0,2649,7.225,,C\n21,0,2,"Fynney, Mr. Joseph J",male,35,0,0,239865,26,,S\n22,1,2,"Beesley, Mr. Lawrence",male,34,0,0,248698,13,D56,S\n23,1,3,"McGowan, Miss. Anna ""Annie""",female,15,0,0,330923,8.0292,,Q\n24,1,1,"Sloper, Mr. William Thompson",male,28,0,0,113788,35.5,A6,S\n25,0,3,"Palsson, Miss. Torborg Danira",female,8,3,1,349909,21.075,,S\n26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)",female,38,1,5,347077,31.3875,,S\n27,0,3,"Emir, Mr. Farred Chehab",male,,0,0,2631,7.225,,C\n28,0,1,"Fortune, Mr. Charles Alexander",male,19,3,2,19950,263,C23 C25 C27,S\n29,1,3,"O\'Dwyer, Miss. Ellen ""Nellie""",female,,0,0,330959,7.8792,,Q\n30,0,3,"Todoroff, Mr. Lalio",male,,0,0,349216,7.8958,,S\n31,0,1,"Uruchurtu, Don. Manuel E",male,40,0,0,PC 17601,27.7208,,C\n32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,,1,0,PC 17569,146.5208,B78,C\n33,1,3,"Glynn, Miss. Mary Agatha",female,,0,0,335677,7.75,,Q\n34,0,2,"Wheadon, Mr. Edward H",male,66,0,0,C.A. 24579,10.5,,S\n35,0,1,"Meyer, Mr. Edgar Joseph",male,28,1,0,PC 17604,82.1708,,C\n36,0,1,"Holverson, Mr. Alexander Oskar",male,42,1,0,113789,52,,S\n37,1,3,"Mamee, Mr. Hanna",male,,0,0,2677,7.2292,,C\n38,0,3,"Cann, Mr. Ernest Charles",male,21,0,0,A./5. 2152,8.05,,S\n39,0,3,"Vander Planke, Miss. Augusta Maria",female,18,2,0,345764,18,,S\n40,1,3,"Nicola-Yarred, Miss. Jamila",female,14,1,0,2651,11.2417,,C\n41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40,1,0,7546,9.475,,S\n42,0,2,"Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)",female,27,1,0,11668,21,,S\n43,0,3,"Kraeff, Mr. Theodor",male,,0,0,349253,7.8958,,C\n44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3,1,2,SC/Paris 2123,41.5792,,C\n45,1,3,"Devaney, Miss. Margaret Delia",female,19,0,0,330958,7.8792,,Q\n46,0,3,"Rogers, Mr. William John",male,,0,0,S.C./A.4. 23567,8.05,,S\n47,0,3,"Lennon, Mr. Denis",male,,1,0,370371,15.5,,Q\n48,1,3,"O\'Driscoll, Miss. Bridget",female,,0,0,14311,7.75,,Q\n49,0,3,"Samaan, Mr. Youssef",male,,2,0,2662,21.6792,,C\n50,0,3,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",female,18,1,0,349237,17.8,,S\n51,0,3,"Panula, Master. Juha Niilo",male,7,4,1,3101295,39.6875,,S\n52,0,3,"Nosworthy, Mr. Richard Cater",male,21,0,0,A/4. 39886,7.8,,S\n53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49,1,0,PC 17572,76.7292,D33,C\n54,1,2,"Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)",female,29,1,0,2926,26,,S\n55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65,0,1,113509,61.9792,B30,C\n56,1,1,"Woolner, Mr. Hugh",male,,0,0,19947,35.5,C52,S\n57,1,2,"Rugg, Miss. Emily",female,21,0,0,C.A. 31026,10.5,,S\n58,0,3,"Novel, Mr. Mansouer",male,28.5,0,0,2697,7.2292,,C\n59,1,2,"West, Miss. Constance Mirium",female,5,1,2,C.A. 34651,27.75,,S\n60,0,3,"Goodwin, Master. William Frederick",male,11,5,2,CA 2144,46.9,,S\n61,0,3,"Sirayanian, Mr. Orsen",male,22,0,0,2669,7.2292,,C\n62,1,1,"Icard, Miss. Amelie",female,38,0,0,113572,80,B28,\n63,0,1,"Harris, Mr. Henry Birkhardt",male,45,1,0,36973,83.475,C83,S\n64,0,3,"Skoog, Master. Harald",male,4,3,2,347088,27.9,,S\n65,0,1,"Stewart, Mr. Albert A",male,,0,0,PC 17605,27.7208,,C\n66,1,3,"Moubarek, Master. Gerios",male,,1,1,2661,15.2458,,C\n67,1,2,"Nye, Mrs. (Elizabeth Ramell)",female,29,0,0,C.A. 29395,10.5,F33,S\n68,0,3,"Crease, Mr. Ernest James",male,19,0,0,S.P. 3464,8.1583,,S\n69,1,3,"Andersson, Miss. Erna Alexandra",female,17,4,2,3101281,7.925,,S\n70,0,3,"Kink, Mr. Vincenz",male,26,2,0,315151,8.6625,,S\n71,0,2,"Jenkin, Mr. Stephen Curnow",male,32,0,0,C.A. 33111,10.5,,S\n72,0,3,"Goodwin, Miss. Lillian Amy",female,16,5,2,CA 2144,46.9,,S\n73,0,2,"Hood, Mr. Ambrose Jr",male,21,0,0,S.O.C. 14879,73.5,,S\n74,0,3,"Chronopoulos, Mr. Apostolos",male,26,1,0,2680,14.4542,,C\n75,1,3,"Bing, Mr. Lee",male,32,0,0,1601,56.4958,,S\n76,0,3,"Moen, Mr. Sigurd Hansen",male,25,0,0,348123,7.65,F G73,S\n77,0,3,"Staneff, Mr. Ivan",male,,0,0,349208,7.8958,,S\n78,0,3,"Moutal, Mr. Rahamin Haim",male,,0,0,374746,8.05,,S\n79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29,,S\n80,1,3,"Dowdell, Miss. Elizabeth",female,30,0,0,364516,12.475,,S\n81,0,3,"Waelens, Mr. Achille",male,22,0,0,345767,9,,S\n82,1,3,"Sheerlinck, Mr. Jan Baptist",male,29,0,0,345779,9.5,,S\n83,1,3,"McDermott, Miss. Brigdet Delia",female,,0,0,330932,7.7875,,Q\n84,0,1,"Carrau, Mr. Francisco M",male,28,0,0,113059,47.1,,S\n85,1,2,"Ilett, Miss. Bertha",female,17,0,0,SO/C 14885,10.5,,S\n86,1,3,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)",female,33,3,0,3101278,15.85,,S\n87,0,3,"Ford, Mr. William Neal",male,16,1,3,W./C. 6608,34.375,,S\n88,0,3,"Slocovski, Mr. Selman Francis",male,,0,0,SOTON/OQ 392086,8.05,,S\n89,1,1,"Fortune, Miss. Mabel Helen",female,23,3,2,19950,263,C23 C25 C27,S\n90,0,3,"Celotti, Mr. Francesco",male,24,0,0,343275,8.05,,S\n91,0,3,"Christmann, Mr. Emil",male,29,0,0,343276,8.05,,S\n92,0,3,"Andreasson, Mr. Paul Edvin",male,20,0,0,347466,7.8542,,S\n93,0,1,"Chaffee, Mr. Herbert Fuller",male,46,1,0,W.E.P. 5734,61.175,E31,S\n94,0,3,"Dean, Mr. Bertram Frank",male,26,1,2,C.A. 2315,20.575,,S\n95,0,3,"Coxon, Mr. Daniel",male,59,0,0,364500,7.25,,S\n96,0,3,"Shorney, Mr. Charles Joseph",male,,0,0,374910,8.05,,S\n97,0,1,"Goldschmidt, Mr. George B",male,71,0,0,PC 17754,34.6542,A5,C\n98,1,1,"Greenfield, Mr. William Bertram",male,23,0,1,PC 17759,63.3583,D10 D12,C\n99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34,0,1,231919,23,,S\n100,0,2,"Kantor, Mr. Sinai",male,34,1,0,244367,26,,S\n101,0,3,"Petranec, Miss. Matilda",female,28,0,0,349245,7.8958,,S\n102,0,3,"Petroff, Mr. Pastcho (""Pentcho"")",male,,0,0,349215,7.8958,,S\n103,0,1,"White, Mr. Richard Frasar",male,21,0,1,35281,77.2875,D26,S\n104,0,3,"Johansson, Mr. Gustaf Joel",male,33,0,0,7540,8.6542,,S\n105,0,3,"Gustafsson, Mr. Anders Vilhelm",male,37,2,0,3101276,7.925,,S\n106,0,3,"Mionoff, Mr. Stoytcho",male,28,0,0,349207,7.8958,,S\n107,1,3,"Salkjelsvik, Miss. Anna Kristine",female,21,0,0,343120,7.65,,S\n108,1,3,"Moss, Mr. Albert Johan",male,,0,0,312991,7.775,,S\n109,0,3,"Rekic, Mr. Tido",male,38,0,0,349249,7.8958,,S\n110,1,3,"Moran, Miss. Bertha",female,,1,0,371110,24.15,,Q\n111,0,1,"Porter, Mr. Walter Chamberlain",male,47,0,0,110465,52,C110,S\n112,0,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,,C\n113,0,3,"Barton, Mr. David John",male,22,0,0,324669,8.05,,S\n114,0,3,"Jussila, Miss. Katriina",female,20,1,0,4136,9.825,,S\n115,0,3,"Attalah, Miss. Malake",female,17,0,0,2627,14.4583,,C\n116,0,3,"Pekoniemi, Mr. Edvard",male,21,0,0,STON/O 2. 3101294,7.925,,S\n117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.75,,Q\n118,0,2,"Turpin, Mr. William John Robert",male,29,1,0,11668,21,,S\n119,0,1,"Baxter, Mr. Quigg Edmond",male,24,0,1,PC 17558,247.5208,B58 B60,C\n120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2,4,2,347082,31.275,,S\n121,0,2,"Hickman, Mr. Stanley George",male,21,2,0,S.O.C. 14879,73.5,,S\n122,0,3,"Moore, Mr. Leonard Charles",male,,0,0,A4. 54510,8.05,,S\n123,0,2,"Nasser, Mr. Nicholas",male,32.5,1,0,237736,30.0708,,C\n124,1,2,"Webber, Miss. Susan",female,32.5,0,0,27267,13,E101,S\n125,0,1,"White, Mr. Percival Wayland",male,54,0,1,35281,77.2875,D26,S\n126,1,3,"Nicola-Yarred, Master. Elias",male,12,1,0,2651,11.2417,,C\n127,0,3,"McMahon, Mr. Martin",male,,0,0,370372,7.75,,Q\n128,1,3,"Madsen, Mr. Fridtjof Arne",male,24,0,0,C 17369,7.1417,,S\n129,1,3,"Peter, Miss. Anna",female,,1,1,2668,22.3583,F E69,C\n130,0,3,"Ekstrom, Mr. Johan",male,45,0,0,347061,6.975,,S\n131,0,3,"Drazenoic, Mr. Jozef",male,33,0,0,349241,7.8958,,C\n132,0,3,"Coelho, Mr. Domingos Fernandeo",male,20,0,0,SOTON/O.Q. 3101307,7.05,,S\n133,0,3,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47,1,0,A/5. 3337,14.5,,S\n134,1,2,"Weisz, Mrs. Leopold (Mathilde Francoise Pede)",female,29,1,0,228414,26,,S\n135,0,2,"Sobey, Mr. Samuel James Hayden",male,25,0,0,C.A. 29178,13,,S\n136,0,2,"Richard, Mr. Emile",male,23,0,0,SC/PARIS 2133,15.0458,,C\n137,1,1,"Newsom, Miss. Helen Monypeny",female,19,0,2,11752,26.2833,D47,S\n138,0,1,"Futrelle, Mr. Jacques Heath",male,37,1,0,113803,53.1,C123,S\n139,0,3,"Osen, Mr. Olaf Elon",male,16,0,0,7534,9.2167,,S\n140,0,1,"Giglio, Mr. Victor",male,24,0,0,PC 17593,79.2,B86,C\n141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,,0,2,2678,15.2458,,C\n142,1,3,"Nysten, Miss. Anna Sofia",female,22,0,0,347081,7.75,,S\n143,1,3,"Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)",female,24,1,0,STON/O2. 3101279,15.85,,S\n144,0,3,"Burke, Mr. Jeremiah",male,19,0,0,365222,6.75,,Q\n145,0,2,"Andrew, Mr. Edgardo Samuel",male,18,0,0,231945,11.5,,S\n146,0,2,"Nicholls, Mr. Joseph Charles",male,19,1,1,C.A. 33112,36.75,,S\n147,1,3,"Andersson, Mr. August Edvard (""Wennerstrom"")",male,27,0,0,350043,7.7958,,S\n148,0,3,"Ford, Miss. Robina Maggie ""Ruby""",female,9,2,2,W./C. 6608,34.375,,S\n149,0,2,"Navratil, Mr. Michel (""Louis M Hoffman"")",male,36.5,0,2,230080,26,F2,S\n150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42,0,0,244310,13,,S\n151,0,2,"Bateman, Rev. Robert James",male,51,0,0,S.O.P. 1166,12.525,,S\n152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22,1,0,113776,66.6,C2,S\n153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.05,,S\n154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5,,S\n155,0,3,"Olsen, Mr. Ole Martin",male,,0,0,Fa 265302,7.3125,,S\n156,0,1,"Williams, Mr. Charles Duane",male,51,0,1,PC 17597,61.3792,,C\n157,1,3,"Gilnagh, Miss. Katherine ""Katie""",female,16,0,0,35851,7.7333,,Q\n158,0,3,"Corn, Mr. Harry",male,30,0,0,SOTON/OQ 392090,8.05,,S\n159,0,3,"Smiljanic, Mr. Mile",male,,0,0,315037,8.6625,,S\n160,0,3,"Sage, Master. Thomas Henry",male,,8,2,CA. 2343,69.55,,S\n161,0,3,"Cribb, Mr. John Hatfield",male,44,0,1,371362,16.1,,S\n162,1,2,"Watt, Mrs. James (Elizabeth ""Bessie"" Inglis Milne)",female,40,0,0,C.A. 33595,15.75,,S\n163,0,3,"Bengtsson, Mr. John Viktor",male,26,0,0,347068,7.775,,S\n164,0,3,"Calic, Mr. Jovo",male,17,0,0,315093,8.6625,,S\n165,0,3,"Panula, Master. Eino Viljami",male,1,4,1,3101295,39.6875,,S\n166,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9,0,2,363291,20.525,,S\n167,1,1,"Chibnall, Mrs. (Edith Martha Bowerman)",female,,0,1,113505,55,E33,S\n168,0,3,"Skoog, Mrs. William (Anna Bernhardina Karlsson)",female,45,1,4,347088,27.9,,S\n169,0,1,"Baumann, Mr. John D",male,,0,0,PC 17318,25.925,,S\n170,0,3,"Ling, Mr. Lee",male,28,0,0,1601,56.4958,,S\n171,0,1,"Van der hoef, Mr. Wyckoff",male,61,0,0,111240,33.5,B19,S\n172,0,3,"Rice, Master. Arthur",male,4,4,1,382652,29.125,,Q\n173,1,3,"Johnson, Miss. Eleanor Ileen",female,1,1,1,347742,11.1333,,S\n174,0,3,"Sivola, Mr. Antti Wilhelm",male,21,0,0,STON/O 2. 3101280,7.925,,S\n175,0,1,"Smith, Mr. James Clinch",male,56,0,0,17764,30.6958,A7,C\n176,0,3,"Klasen, Mr. Klas Albin",male,18,1,1,350404,7.8542,,S\n177,0,3,"Lefebre, Master. Henry Forbes",male,,3,1,4133,25.4667,,S\n178,0,1,"Isham, Miss. Ann Elizabeth",female,50,0,0,PC 17595,28.7125,C49,C\n179,0,2,"Hale, Mr. Reginald",male,30,0,0,250653,13,,S\n180,0,3,"Leonard, Mr. Lionel",male,36,0,0,LINE,0,,S\n181,0,3,"Sage, Miss. Constance Gladys",female,,8,2,CA. 2343,69.55,,S\n182,0,2,"Pernot, Mr. Rene",male,,0,0,SC/PARIS 2131,15.05,,C\n183,0,3,"Asplund, Master. Clarence Gustaf Hugo",male,9,4,2,347077,31.3875,,S\n184,1,2,"Becker, Master. Richard F",male,1,2,1,230136,39,F4,S\n185,1,3,"Kink-Heilmann, Miss. Luise Gretchen",female,4,0,2,315153,22.025,,S\n186,0,1,"Rood, Mr. Hugh Roscoe",male,,0,0,113767,50,A32,S\n187,1,3,"O\'Brien, Mrs. Thomas (Johanna ""Hannah"" Godfrey)",female,,1,0,370365,15.5,,Q\n188,1,1,"Romaine, Mr. Charles Hallace (""Mr C Rolmane"")",male,45,0,0,111428,26.55,,S\n189,0,3,"Bourke, Mr. John",male,40,1,1,364849,15.5,,Q\n190,0,3,"Turcin, Mr. Stjepan",male,36,0,0,349247,7.8958,,S\n191,1,2,"Pinsky, Mrs. (Rosa)",female,32,0,0,234604,13,,S\n192,0,2,"Carbines, Mr. William",male,19,0,0,28424,13,,S\n193,1,3,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19,1,0,350046,7.8542,,S\n194,1,2,"Navratil, Master. Michel M",male,3,1,1,230080,26,F2,S\n195,1,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44,0,0,PC 17610,27.7208,B4,C\n196,1,1,"Lurette, Miss. Elise",female,58,0,0,PC 17569,146.5208,B80,C\n197,0,3,"Mernagh, Mr. Robert",male,,0,0,368703,7.75,,Q\n198,0,3,"Olsen, Mr. Karl Siegwart Andreas",male,42,0,1,4579,8.4042,,S\n199,1,3,"Madigan, Miss. Margaret ""Maggie""",female,,0,0,370370,7.75,,Q\n200,0,2,"Yrois, Miss. Henriette (""Mrs Harbeck"")",female,24,0,0,248747,13,,S\n201,0,3,"Vande Walle, Mr. Nestor Cyriel",male,28,0,0,345770,9.5,,S\n202,0,3,"Sage, Mr. Frederick",male,,8,2,CA. 2343,69.55,,S\n203,0,3,"Johanson, Mr. Jakob Alfred",male,34,0,0,3101264,6.4958,,S\n204,0,3,"Youseff, Mr. Gerious",male,45.5,0,0,2628,7.225,,C\n205,1,3,"Cohen, Mr. Gurshon ""Gus""",male,18,0,0,A/5 3540,8.05,,S\n206,0,3,"Strom, Miss. Telma Matilda",female,2,0,1,347054,10.4625,G6,S\n207,0,3,"Backstrom, Mr. Karl Alfred",male,32,1,0,3101278,15.85,,S\n208,1,3,"Albimona, Mr. Nassef Cassem",male,26,0,0,2699,18.7875,,C\n209,1,3,"Carr, Miss. Helen ""Ellen""",female,16,0,0,367231,7.75,,Q\n210,1,1,"Blank, Mr. Henry",male,40,0,0,112277,31,A31,C\n211,0,3,"Ali, Mr. Ahmed",male,24,0,0,SOTON/O.Q. 3101311,7.05,,S\n212,1,2,"Cameron, Miss. Clear Annie",female,35,0,0,F.C.C. 13528,21,,S\n213,0,3,"Perkin, Mr. John Henry",male,22,0,0,A/5 21174,7.25,,S\n214,0,2,"Givard, Mr. Hans Kristensen",male,30,0,0,250646,13,,S\n215,0,3,"Kiernan, Mr. Philip",male,,1,0,367229,7.75,,Q\n216,1,1,"Newell, Miss. Madeleine",female,31,1,0,35273,113.275,D36,C\n217,1,3,"Honkanen, Miss. Eliina",female,27,0,0,STON/O2. 3101283,7.925,,S\n218,0,2,"Jacobsohn, Mr. Sidney Samuel",male,42,1,0,243847,27,,S\n219,1,1,"Bazzani, Miss. Albina",female,32,0,0,11813,76.2917,D15,C\n220,0,2,"Harris, Mr. Walter",male,30,0,0,W/C 14208,10.5,,S\n221,1,3,"Sunderland, Mr. Victor Francis",male,16,0,0,SOTON/OQ 392089,8.05,,S\n222,0,2,"Bracken, Mr. James H",male,27,0,0,220367,13,,S\n223,0,3,"Green, Mr. George Henry",male,51,0,0,21440,8.05,,S\n224,0,3,"Nenkoff, Mr. Christo",male,,0,0,349234,7.8958,,S\n225,1,1,"Hoyt, Mr. Frederick Maxfield",male,38,1,0,19943,90,C93,S\n226,0,3,"Berglund, Mr. Karl Ivar Sven",male,22,0,0,PP 4348,9.35,,S\n227,1,2,"Mellors, Mr. William John",male,19,0,0,SW/PP 751,10.5,,S\n228,0,3,"Lovell, Mr. John Hall (""Henry"")",male,20.5,0,0,A/5 21173,7.25,,S\n229,0,2,"Fahlstrom, Mr. Arne Jonas",male,18,0,0,236171,13,,S\n230,0,3,"Lefebre, Miss. Mathilde",female,,3,1,4133,25.4667,,S\n231,1,1,"Harris, Mrs. Henry Birkhardt (Irene Wallach)",female,35,1,0,36973,83.475,C83,S\n232,0,3,"Larsson, Mr. Bengt Edvin",male,29,0,0,347067,7.775,,S\n233,0,2,"Sjostedt, Mr. Ernst Adolf",male,59,0,0,237442,13.5,,S\n234,1,3,"Asplund, Miss. Lillian Gertrud",female,5,4,2,347077,31.3875,,S\n235,0,2,"Leyson, Mr. Robert William Norman",male,24,0,0,C.A. 29566,10.5,,S\n236,0,3,"Harknett, Miss. Alice Phoebe",female,,0,0,W./C. 6609,7.55,,S\n237,0,2,"Hold, Mr. Stephen",male,44,1,0,26707,26,,S\n238,1,2,"Collyer, Miss. Marjorie ""Lottie""",female,8,0,2,C.A. 31921,26.25,,S\n239,0,2,"Pengelly, Mr. Frederick William",male,19,0,0,28665,10.5,,S\n240,0,2,"Hunt, Mr. George Henry",male,33,0,0,SCO/W 1585,12.275,,S\n241,0,3,"Zabour, Miss. Thamine",female,,1,0,2665,14.4542,,C\n242,1,3,"Murphy, Miss. Katherine ""Kate""",female,,1,0,367230,15.5,,Q\n243,0,2,"Coleridge, Mr. Reginald Charles",male,29,0,0,W./C. 14263,10.5,,S\n244,0,3,"Maenpaa, Mr. Matti Alexanteri",male,22,0,0,STON/O 2. 3101275,7.125,,S\n245,0,3,"Attalah, Mr. Sleiman",male,30,0,0,2694,7.225,,C\n246,0,1,"Minahan, Dr. William Edward",male,44,2,0,19928,90,C78,Q\n247,0,3,"Lindahl, Miss. Agda Thorilda Viktoria",female,25,0,0,347071,7.775,,S\n248,1,2,"Hamalainen, Mrs. William (Anna)",female,24,0,2,250649,14.5,,S\n249,1,1,"Beckwith, Mr. Richard Leonard",male,37,1,1,11751,52.5542,D35,S\n250,0,2,"Carter, Rev. Ernest Courtenay",male,54,1,0,244252,26,,S\n251,0,3,"Reed, Mr. James George",male,,0,0,362316,7.25,,S\n252,0,3,"Strom, Mrs. Wilhelm (Elna Matilda Persson)",female,29,1,1,347054,10.4625,G6,S\n253,0,1,"Stead, Mr. William Thomas",male,62,0,0,113514,26.55,C87,S\n254,0,3,"Lobb, Mr. William Arthur",male,30,1,0,A/5. 3336,16.1,,S\n255,0,3,"Rosblom, Mrs. Viktor (Helena Wilhelmina)",female,41,0,2,370129,20.2125,,S\n256,1,3,"Touma, Mrs. Darwis (Hanne Youssef Razi)",female,29,0,2,2650,15.2458,,C\n257,1,1,"Thorne, Mrs. Gertrude Maybelle",female,,0,0,PC 17585,79.2,,C\n258,1,1,"Cherry, Miss. Gladys",female,30,0,0,110152,86.5,B77,S\n259,1,1,"Ward, Miss. Anna",female,35,0,0,PC 17755,512.3292,,C\n260,1,2,"Parrish, Mrs. (Lutie Davis)",female,50,0,1,230433,26,,S\n261,0,3,"Smith, Mr. Thomas",male,,0,0,384461,7.75,,Q\n262,1,3,"Asplund, Master. Edvin Rojj Felix",male,3,4,2,347077,31.3875,,S\n263,0,1,"Taussig, Mr. Emil",male,52,1,1,110413,79.65,E67,S\n264,0,1,"Harrison, Mr. William",male,40,0,0,112059,0,B94,S\n265,0,3,"Henry, Miss. Delia",female,,0,0,382649,7.75,,Q\n266,0,2,"Reeves, Mr. David",male,36,0,0,C.A. 17248,10.5,,S\n267,0,3,"Panula, Mr. Ernesti Arvid",male,16,4,1,3101295,39.6875,,S\n268,1,3,"Persson, Mr. Ernst Ulrik",male,25,1,0,347083,7.775,,S\n269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58,0,1,PC 17582,153.4625,C125,S\n270,1,1,"Bissette, Miss. Amelia",female,35,0,0,PC 17760,135.6333,C99,S\n271,0,1,"Cairns, Mr. Alexander",male,,0,0,113798,31,,S\n272,1,3,"Tornquist, Mr. William Henry",male,25,0,0,LINE,0,,S\n273,1,2,"Mellinger, Mrs. (Elizabeth Anne Maidment)",female,41,0,1,250644,19.5,,S\n274,0,1,"Natsch, Mr. Charles H",male,37,0,1,PC 17596,29.7,C118,C\n275,1,3,"Healy, Miss. Hanora ""Nora""",female,,0,0,370375,7.75,,Q\n276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63,1,0,13502,77.9583,D7,S\n277,0,3,"Lindblom, Miss. Augusta Charlotta",female,45,0,0,347073,7.75,,S\n278,0,2,"Parkes, Mr. Francis ""Frank""",male,,0,0,239853,0,,S\n279,0,3,"Rice, Master. Eric",male,7,4,1,382652,29.125,,Q\n280,1,3,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35,1,1,C.A. 2673,20.25,,S\n281,0,3,"Duane, Mr. Frank",male,65,0,0,336439,7.75,,Q\n282,0,3,"Olsson, Mr. Nils Johan Goransson",male,28,0,0,347464,7.8542,,S\n283,0,3,"de Pelsmaeker, Mr. Alfons",male,16,0,0,345778,9.5,,S\n284,1,3,"Dorking, Mr. Edward Arthur",male,19,0,0,A/5. 10482,8.05,,S\n285,0,1,"Smith, Mr. Richard William",male,,0,0,113056,26,A19,S\n286,0,3,"Stankovic, Mr. Ivan",male,33,0,0,349239,8.6625,,C\n287,1,3,"de Mulder, Mr. Theodore",male,30,0,0,345774,9.5,,S\n288,0,3,"Naidenoff, Mr. Penko",male,22,0,0,349206,7.8958,,S\n289,1,2,"Hosono, Mr. Masabumi",male,42,0,0,237798,13,,S\n290,1,3,"Connolly, Miss. Kate",female,22,0,0,370373,7.75,,Q\n291,1,1,"Barber, Miss. Ellen ""Nellie""",female,26,0,0,19877,78.85,,S\n292,1,1,"Bishop, Mrs. Dickinson H (Helen Wal

In [12]:
parsed_data = [x.split(',') for x in response.text.splitlines()]

print(parsed_data)  # This will print the parsed data as a list of lists, where each inner list represents a row of the dataset.
# Keeps only the first 12 columns for every row
cleaned_data = [row[:12] for row in parsed_data]

df = pd.DataFrame(cleaned_data[1:], columns=cleaned_data[0])

[['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'], ['1', '0', '3', '"Braund', ' Mr. Owen Harris"', 'male', '22', '1', '0', 'A/5 21171', '7.25', '', 'S'], ['2', '1', '1', '"Cumings', ' Mrs. John Bradley (Florence Briggs Thayer)"', 'female', '38', '1', '0', 'PC 17599', '71.2833', 'C85', 'C'], ['3', '1', '3', '"Heikkinen', ' Miss. Laina"', 'female', '26', '0', '0', 'STON/O2. 3101282', '7.925', '', 'S'], ['4', '1', '1', '"Futrelle', ' Mrs. Jacques Heath (Lily May Peel)"', 'female', '35', '1', '0', '113803', '53.1', 'C123', 'S'], ['5', '0', '3', '"Allen', ' Mr. William Henry"', 'male', '35', '0', '0', '373450', '8.05', '', 'S'], ['6', '0', '3', '"Moran', ' Mr. James"', 'male', '', '0', '0', '330877', '8.4583', '', 'Q'], ['7', '0', '1', '"McCarthy', ' Mr. Timothy J"', 'male', '54', '0', '0', '17463', '51.8625', 'E46', 'S'], ['8', '0', '3', '"Palsson', ' Master. Gosta Leonard"', 'male', '2', '3', '1', '349909', '21.075', '', 'S'], ['9', '1', '3', '"Johnson', ' Mrs. Oscar W (Elisabeth Vilhelmina Berg)"', 'female', '27', '0', '2', '347742', '11.1333', '', 'S'], ['10', '1', '2', '"Nasser', ' Mrs. Nicholas (Adele Achem)"', 'female', '14', '1', '0', '237736', '30.0708', '', 'C'], ['11', '1', '3', '"Sandstrom', ' Miss. Marguerite Rut"', 'female', '4', '1', '1', 'PP 9549', '16.7', 'G6', 'S'], ['12', '1', '1', '"Bonnell', ' Miss. Elizabeth"', 'female', '58', '0', '0', '113783', '26.55', 'C103', 'S'], ['13', '0', '3', '"Saundercock', ' Mr. William Henry"', 'male', '20', '0', '0', 'A/5. 2151', '8.05', '', 'S'], ['14', '0', '3', '"Andersson', ' Mr. Anders Johan"', 'male', '39', '1', '5', '347082', '31.275', '', 'S'], ['15', '0', '3', '"Vestrom', ' Miss. Hulda Amanda Adolfina"', 'female', '14', '0', '0', '350406', '7.8542', '', 'S'], ['16', '1', '2', '"Hewlett', ' Mrs. (Mary D Kingcome) "', 'female', '55', '0', '0', '248706', '16', '', 'S'], ['17', '0', '3', '"Rice', ' Master. Eugene"', 'male', '2', '4', '1', '382652', '29.125', '', 'Q'], ['18', '1', '2', '"Williams', ' Mr. Charles Eugene"', 'male', '', '0', '0', '244373', '13', '', 'S'], ['19', '0', '3', '"Vander Planke', ' Mrs. Julius (Emelia Maria Vandemoortele)"', 'female', '31', '1', '0', '345763', '18', '', 'S'], ['20', '1', '3', '"Masselmani', ' Mrs. Fatima"', 'female', '', '0', '0', '2649', '7.225', '', 'C'], ['21', '0', '2', '"Fynney', ' Mr. Joseph J"', 'male', '35', '0', '0', '239865', '26', '', 'S'], ['22', '1', '2', '"Beesley', ' Mr. Lawrence"', 'male', '34', '0', '0', '248698', '13', 'D56', 'S'], ['23', '1', '3', '"McGowan', ' Miss. Anna ""Annie"""', 'female', '15', '0', '0', '330923', '8.0292', '', 'Q'], ['24', '1', '1', '"Sloper', ' Mr. William Thompson"', 'male', '28', '0', '0', '113788', '35.5', 'A6', 'S'], ['25', '0', '3', '"Palsson', ' Miss. Torborg Danira"', 'female', '8', '3', '1', '349909', '21.075', '', 'S'], ['26', '1', '3', '"Asplund', ' Mrs. Carl Oscar (Selma Augusta Emilia Johansson)"', 'female', '38', '1', '5', '347077', '31.3875', '', 'S'], ['27', '0', '3', '"Emir', ' Mr. Farred Chehab"', 'male', '', '0', '0', '2631', '7.225', '', 'C'], ['28', '0', '1', '"Fortune', ' Mr. Charles Alexander"', 'male', '19', '3', '2', '19950', '263', 'C23 C25 C27', 'S'], ['29', '1', '3', '"O\'Dwyer', ' Miss. Ellen ""Nellie"""', 'female', '', '0', '0', '330959', '7.8792', '', 'Q'], ['30', '0', '3', '"Todoroff', ' Mr. Lalio"', 'male', '', '0', '0', '349216', '7.8958', '', 'S'], ['31', '0', '1', '"Uruchurtu', ' Don. Manuel E"', 'male', '40', '0', '0', 'PC 17601', '27.7208', '', 'C'], ['32', '1', '1', '"Spencer', ' Mrs. William Augustus (Marie Eugenie)"', 'female', '', '1', '0', 'PC 17569', '146.5208', 'B78', 'C'], ['33', '1', '3', '"Glynn', ' Miss. Mary Agatha"', 'female', '', '0', '0', '335677', '7.75', '', 'Q'], ['34', '0', '2', '"Wheadon', ' Mr. Edward H"', 'male', '66', '0', '0', 'C.A. 24579', '10.5', '', 'S'], ['35', '0', '1', '"Meyer', ' Mr. Edgar Joseph"', 'male', '28', '1', '0', 'PC 17604', '82.1708', '', 'C'], ['36', '0', '1', '"Holverson', ' Mr. Alexander Oskar"', 'male', '42', '1', '0', '113789', '52', '', 'S'], ['37', '1', '3', '"Mamee', ' Mr. Hanna"', 'male', '', '0', '0', '2677', '7.2292', '', 'C'], ['38', '0', '3', '"Cann', ' Mr. Ernest Charles"', 'male', '21', '0', '0', 'A./5. 2152', '8.05', '', 'S'], ['39', '0', '3', '"Vander Planke', ' Miss. Augusta Maria"', 'female', '18', '2', '0', '345764', '18', '', 'S'], ['40', '1', '3', '"Nicola-Yarred', ' Miss. Jamila"', 'female', '14', '1', '0', '2651', '11.2417', '', 'C'], ['41', '0', '3', '"Ahlin', ' Mrs. Johan (Johanna Persdotter Larsson)"', 'female', '40', '1', '0', '7546', '9.475', '', 'S'], ['42', '0', '2', '"Turpin', ' Mrs. William John Robert (Dorothy Ann Wonnacott)"', 'female', '27', '1', '0', '11668', '21', '', 'S'], ['43', '0', '3', '"Kraeff', ' Mr. Theodor"', 'male', '', '0', '0', '349253', '7.8958', '', 'C'], ['44', '1', '2', '"Laroche', ' Miss. Simonne Marie Anne Andree"', 'female', '3', '1', '2', 'SC/Paris 2123', '41.5792', '', 'C'], ['45', '1', '3', '"Devaney', ' Miss. Margaret Delia"', 'female', '19', '0', '0', '330958', '7.8792', '', 'Q'], ['46', '0', '3', '"Rogers', ' Mr. William John"', 'male', '', '0', '0', 'S.C./A.4. 23567', '8.05', '', 'S'], ['47', '0', '3', '"Lennon', ' Mr. Denis"', 'male', '', '1', '0', '370371', '15.5', '', 'Q'], ['48', '1', '3', '"O\'Driscoll', ' Miss. Bridget"', 'female', '', '0', '0', '14311', '7.75', '', 'Q'], ['49', '0', '3', '"Samaan', ' Mr. Youssef"', 'male', '', '2', '0', '2662', '21.6792', '', 'C'], ['50', '0', '3', '"Arnold-Franchi', ' Mrs. Josef (Josefine Franchi)"', 'female', '18', '1', '0', '349237', '17.8', '', 'S'], ['51', '0', '3', '"Panula', ' Master. Juha Niilo"', 'male', '7', '4', '1', '3101295', '39.6875', '', 'S'], ['52', '0', '3', '"Nosworthy', ' Mr. Richard Cater"', 'male', '21', '0', '0', 'A/4. 39886', '7.8', '', 'S'], ['53', '1', '1', '"Harper', ' Mrs. Henry Sleeper (Myna Haxtun)"', 'female', '49', '1', '0', 'PC 17572', '76.7292', 'D33', 'C'], ['54', '1', '2', '"Faunthorpe', ' Mrs. Lizzie (Elizabeth Anne Wilkinson)"', 'female', '29', '1', '0', '2926', '26', '', 'S'], ['55', '0', '1', '"Ostby', ' Mr. Engelhart Cornelius"', 'male', '65', '0', '1', '113509', '61.9792', 'B30', 'C'], ['56', '1', '1', '"Woolner', ' Mr. Hugh"', 'male', '', '0', '0', '19947', '35.5', 'C52', 'S'], ['57', '1', '2', '"Rugg', ' Miss. Emily"', 'female', '21', '0', '0', 'C.A. 31026', '10.5', '', 'S'], ['58', '0', '3', '"Novel', ' Mr. Mansouer"', 'male', '28.5', '0', '0', '2697', '7.2292', '', 'C'], ['59', '1', '2', '"West', ' Miss. Constance Mirium"', 'female', '5', '1', '2', 'C.A. 34651', '27.75', '', 'S'], ['60', '0', '3', '"Goodwin', ' Master. William Frederick"', 'male', '11', '5', '2', 'CA 2144', '46.9', '', 'S'], ['61', '0', '3', '"Sirayanian', ' Mr. Orsen"', 'male', '22', '0', '0', '2669', '7.2292', '', 'C'], ['62', '1', '1', '"Icard', ' Miss. Amelie"', 'female', '38', '0', '0', '113572', '80', 'B28', ''], ['63', '0', '1', '"Harris', ' Mr. Henry Birkhardt"', 'male', '45', '1', '0', '36973', '83.475', 'C83', 'S'], ['64', '0', '3', '"Skoog', ' Master. Harald"', 'male', '4', '3', '2', '347088', '27.9', '', 'S'], ['65', '0', '1', '"Stewart', ' Mr. Albert A"', 'male', '', '0', '0', 'PC 17605', '27.7208', '', 'C'], ['66', '1', '3', '"Moubarek', ' Master. Gerios"', 'male', '', '1', '1', '2661', '15.2458', '', 'C'], ['67', '1', '2', '"Nye', ' Mrs. (Elizabeth Ramell)"', 'female', '29', '0', '0', 'C.A. 29395', '10.5', 'F33', 'S'], ['68', '0', '3', '"Crease', ' Mr. Ernest James"', 'male', '19', '0', '0', 'S.P. 3464', '8.1583', '', 'S'], ['69', '1', '3', '"Andersson', ' Miss. Erna Alexandra"', 'female', '17', '4', '2', '3101281', '7.925', '', 'S'], ['70', '0', '3', '"Kink', ' Mr. Vincenz"', 'male', '26', '2', '0', '315151', '8.6625', '', 'S'], ['71', '0', '2', '"Jenkin', ' Mr. Stephen Curnow"', 'male', '32', '0', '0', 'C.A. 33111', '10.5', '', 'S'], ['72', '0', '3', '"Goodwin', ' Miss. Lillian Amy"', 'female', '16', '5', '2', 'CA 2144', '46.9', '', 'S'], ['73', '0', '2', '"Hood', ' Mr. Ambrose Jr"', 'male', '21', '0', '0', 'S.O.C. 14879', '73.5', '', 'S'], ['74', '0', '3', '"Chronopoulos', ' Mr. Apostolos"', 'male', '26', '1', '0', '2680', '14.4542', '', 'C'], ['75', '1', '3', '"Bing', ' Mr. Lee"', 'male', '32', '0', '0', '1601', '56.4958', '', 'S'], ['76', '0', '3', '"Moen', ' Mr. Sigurd Hansen"', 'male', '25', '0', '0', '348123', '7.65', 'F G73', 'S'], ['77', '0', '3', '"Staneff', ' Mr. Ivan"', 'male', '', '0', '0', '349208', '7.8958', '', 'S'], ['78', '0', '3', '"Moutal', ' Mr. Rahamin Haim"', 'male', '', '0', '0', '374746', '8.05', '', 'S'], ['79', '1', '2', '"Caldwell', ' Master. Alden Gates"', 'male', '0.83', '0', '2', '248738', '29', '', 'S'], ['80', '1', '3', '"Dowdell', ' Miss. Elizabeth"', 'female', '30', '0', '0', '364516', '12.475', '', 'S'], ['81', '0', '3', '"Waelens', ' Mr. Achille"', 'male', '22', '0', '0', '345767', '9', '', 'S'], ['82', '1', '3', '"Sheerlinck', ' Mr. Jan Baptist"', 'male', '29', '0', '0', '345779', '9.5', '', 'S'], ['83', '1', '3', '"McDermott', ' Miss. Brigdet Delia"', 'female', '', '0', '0', '330932', '7.7875', '', 'Q'], ['84', '0', '1', '"Carrau', ' Mr. Francisco M"', 'male', '28', '0', '0', '113059', '47.1', '', 'S'], ['85', '1', '2', '"Ilett', ' Miss. Bertha"', 'female', '17', '0', '0', 'SO/C 14885', '10.5', '', 'S'], ['86', '1', '3', '"Backstrom', ' Mrs. Karl Alfred (Maria Mathilda Gustafsson)"', 'female', '33', '3', '0', '3101278', '15.85', '', 'S'], ['87', '0', '3', '"Ford', ' Mr. William Neal"', 'male', '16', '1', '3', 'W./C. 6608', '34.375', '', 'S'], ['88', '0', '3', '"Slocovski', ' Mr. Selman Francis"', 'male', '', '0', '0', 'SOTON/OQ 392086', '8.05', '', 'S'], ['89', '1', '1', '"Fortune', ' Miss. Mabel Helen"', 'female', '23', '3', '2', '19950', '263', 'C23 C25 C27', 'S'], ['90', '0', '3', '"Celotti', ' Mr. Francesco"', 'male', '24', '0', '0', '343275', '8.05', '', 'S'], ['91', '0', '3', '"Christmann', ' Mr. Emil"', 'male', '29', '0', '0', '343276', '8.05', '', 'S'], ['92', '0', '3', '"Andreasson', ' Mr. Paul Edvin"', 'male', '20', '0', '0', '347466', '7.8542', '', 'S'], ['93', '0', '1', '"Chaffee', ' Mr. Herbert Fuller"', 'male', '46', '1', '0', 'W.E.P. 5734', '61.175', 'E31', 'S'], ['94', '0', '3', '"Dean', ' Mr. Bertram Frank"', 'male', '26', '1', '2', 'C.A. 2315', '20.575', '', 'S'], ['95', '0', '3', '"Coxon', ' Mr. Daniel"', 'male', '59', '0', '0', '364500', '7.25', '', 'S'], ['96', '0', '3', '"Shorney', ' Mr. Charles Joseph"', 'male', '', '0', '0', '374910', '8.05', '', 'S'], ['97', '0', '1', '"Goldschmidt', ' Mr. George B"', 'male', '71', '0', '0', 'PC 17754', '34.6542', 'A5', 'C'], ['98', '1', '1', '"Greenfield', ' Mr. William Bertram"', 'male', '23', '0', '1', 'PC 17759', '63.3583', 'D10 D12', 'C'], ['99', '1', '2', '"Doling', ' Mrs. John T (Ada Julia Bone)"', 'female', '34', '0', '1', '231919', '23', '', 'S'], ['100', '0', '2', '"Kantor', ' Mr. Sinai"', 'male', '34', '1', '0', '244367', '26', '', 'S'], ['101', '0', '3', '"Petranec', ' Miss. Matilda"', 'female', '28', '0', '0', '349245', '7.8958', '', 'S'], ['102', '0', '3', '"Petroff', ' Mr. Pastcho (""Pentcho"")"', 'male', '', '0', '0', '349215', '7.8958', '', 'S'], ['103', '0', '1', '"White', ' Mr. Richard Frasar"', 'male', '21', '0', '1', '35281', '77.2875', 'D26', 'S'], ['104', '0', '3', '"Johansson', ' Mr. Gustaf Joel"', 'male', '33', '0', '0', '7540', '8.6542', '', 'S'], ['105', '0', '3', '"Gustafsson', ' Mr. Anders Vilhelm"', 'male', '37', '2', '0', '3101276', '7.925', '', 'S'], ['106', '0', '3', '"Mionoff', ' Mr. Stoytcho"', 'male', '28', '0', '0', '349207', '7.8958', '', 'S'], ['107', '1', '3', '"Salkjelsvik', ' Miss. Anna Kristine"', 'female', '21', '0', '0', '343120', '7.65', '', 'S'], ['108', '1', '3', '"Moss', ' Mr. Albert Johan"', 'male', '', '0', '0', '312991', '7.775', '', 'S'], ['109', '0', '3', '"Rekic', ' Mr. Tido"', 'male', '38', '0', '0', '349249', '7.8958', '', 'S'], ['110', '1', '3', '"Moran', ' Miss. Bertha"', 'female', '', '1', '0', '371110', '24.15', '', 'Q'], ['111', '0', '1', '"Porter', ' Mr. Walter Chamberlain"', 'male', '47', '0', '0', '110465', '52', 'C110', 'S'], ['112', '0', '3', '"Zabour', ' Miss. Hileni"', 'female', '14.5', '1', '0', '2665', '14.4542', '', 'C'], ['113', '0', '3', '"Barton', ' Mr. David John"', 'male', '22', '0', '0', '324669', '8.05', '', 'S'], ['114', '0', '3', '"Jussila', ' Miss. Katriina"', 'female', '20', '1', '0', '4136', '9.825', '', 'S'], ['115', '0', '3', '"Attalah', ' Miss. Malake"', 'female', '17', '0', '0', '2627', '14.4583', '', 'C'], ['116', '0', '3', '"Pekoniemi', ' Mr. Edvard"', 'male', '21', '0', '0', 'STON/O 2. 3101294', '7.925', '', 'S'], ['117', '0', '3', '"Connors', ' Mr. Patrick"', 'male', '70.5', '0', '0', '370369', '7.75', '', 'Q'], ['118', '0', '2', '"Turpin', ' Mr. William John Robert"', 'male', '29', '1', '0', '11668', '21', '', 'S'], ['119', '0', '1', '"Baxter', ' Mr. Quigg Edmond"', 'male', '24', '0', '1', 'PC 17558', '247.5208', 'B58 B60', 'C'], ['120', '0', '3', '"Andersson', ' Miss. Ellis Anna Maria"', 'female', '2', '4', '2', '347082', '31.275', '', 'S'], ['121', '0', '2', '"Hickman', ' Mr. Stanley George"', 'male', '21', '2', '0', 'S.O.C. 14879', '73.5', '', 'S'], ['122', '0', '3', '"Moore', ' Mr. Leonard Charles"', 'male', '', '0', '0', 'A4. 54510', '8.05', '', 'S'], ['123', '0', '2', '"Nasser', ' Mr. Nicholas"', 'male', '32.5', '1', '0', '237736', '30.0708', '', 'C'], ['124', '1', '2', '"Webber', ' Miss. Susan"', 'female', '32.5', '0', '0', '27267', '13', 'E101', 'S'], ['125', '0', '1', '"White', ' Mr. Percival Wayland"', 'male', '54', '0', '1', '35281', '77.2875', 'D26', 'S'], ['126', '1', '3', '"Nicola-Yarred', ' Master. Elias"', 'male', '12', '1', '0', '2651', '11.2417', '', 'C'], ['127', '0', '3', '"McMahon', ' Mr. Martin"', 'male', '', '0', '0', '370372', '7.75', '', 'Q'], ['128', '1', '3', '"Madsen', ' Mr. Fridtjof Arne"', 'male', '24', '0', '0', 'C 17369', '7.1417', '', 'S'], ['129', '1', '3', '"Peter', ' Miss. Anna"', 'female', '', '1', '1', '2668', '22.3583', 'F E69', 'C'], ['130', '0', '3', '"Ekstrom', ' Mr. Johan"', 'male', '45', '0', '0', '347061', '6.975', '', 'S'], ['131', '0', '3', '"Drazenoic', ' Mr. Jozef"', 'male', '33', '0', '0', '349241', '7.8958', '', 'C'], ['132', '0', '3', '"Coelho', ' Mr. Domingos Fernandeo"', 'male', '20', '0', '0', 'SOTON/O.Q. 3101307', '7.05', '', 'S'], ['133', '0', '3', '"Robins', ' Mrs. Alexander A (Grace Charity Laury)"', 'female', '47', '1', '0', 'A/5. 3337', '14.5', '', 'S'], ['134', '1', '2', '"Weisz', ' Mrs. Leopold (Mathilde Francoise Pede)"', 'female', '29', '1', '0', '228414', '26', '', 'S'], ['135', '0', '2', '"Sobey', ' Mr. Samuel James Hayden"', 'male', '25', '0', '0', 'C.A. 29178', '13', '', 'S'], ['136', '0', '2', '"Richard', ' Mr. Emile"', 'male', '23', '0', '0', 'SC/PARIS 2133', '15.0458', '', 'C'], ['137', '1', '1', '"Newsom', ' Miss. Helen Monypeny"', 'female', '19', '0', '2', '11752', '26.2833', 'D47', 'S'], ['138', '0', '1', '"Futrelle', ' Mr. Jacques Heath"', 'male', '37', '1', '0', '113803', '53.1', 'C123', 'S'], ['139', '0', '3', '"Osen', ' Mr. Olaf Elon"', 'male', '16', '0', '0', '7534', '9.2167', '', 'S'], ['140', '0', '1', '"Giglio', ' Mr. Victor"', 'male', '24', '0', '0', 'PC 17593', '79.2', 'B86', 'C'], ['141', '0', '3', '"Boulos', ' Mrs. Joseph (Sultana)"', 'female', '', '0', '2', '2678', '15.2458', '', 'C'], ['142', '1', '3', '"Nysten', ' Miss. Anna Sofia"', 'female', '22', '0', '0', '347081', '7.75', '', 'S'], ['143', '1', '3', '"Hakkarainen', ' Mrs. Pekka Pietari (Elin Matilda Dolck)"', 'female', '24', '1', '0', 'STON/O2. 3101279', '15.85', '', 'S'], ['144', '0', '3', '"Burke', ' Mr. Jeremiah"', 'male', '19', '0', '0', '365222', '6.75', '', 'Q'], ['145', '0', '2', '"Andrew', ' Mr. Edgardo Samuel"', 'male', '18', '0', '0', '231945', '11.5', '', 'S'], ['146', '0', '2', '"Nicholls', ' Mr. Joseph Charles"', 'male', '19', '1', '1', 'C.A. 33112', '36.75', '', 'S'], ['147', '1', '3', '"Andersson', ' Mr. August Edvard (""Wennerstrom"")"', 'male', '27', '0', '0', '350043', '7.7958', '', 'S'], ['148', '0', '3', '"Ford', ' Miss. Robina Maggie ""Ruby"""', 'female', '9', '2', '2', 'W./C. 6608', '34.375', '', 'S'], ['149', '0', '2', '"Navratil', ' Mr. Michel (""Louis M Hoffman"")"', 'male', '36.5', '0', '2', '230080', '26', 'F2', 'S'], ['150', '0', '2', '"Byles', ' Rev. Thomas Roussel Davids"', 'male', '42', '0', '0', '244310', '13', '', 'S'], ['151', '0', '2', '"Bateman', ' Rev. Robert James"', 'male', '51', '0', '0', 'S.O.P. 1166', '12.525', '', 'S'], ['152', '1', '1', '"Pears', ' Mrs. Thomas (Edith Wearne)"', 'female', '22', '1', '0', '113776', '66.6', 'C2', 'S'], ['153', '0', '3', '"Meo', ' Mr. Alfonzo"', 'male', '55.5', '0', '0', 'A.5. 11206', '8.05', '', 'S'], ['154', '0', '3', '"van Billiard', ' Mr. Austin Blyler"', 'male', '40.5', '0', '2', 'A/5. 851', '14.5', '', 'S'], ['155', '0', '3', '"Olsen', ' Mr. Ole Martin"', 'male', '', '0', '0', 'Fa 265302', '7.3125', '', 'S'], ['156', '0', '1', '"Williams', ' Mr. Charles Duane"', 'male', '51', '0', '1', 'PC 17597', '61.3792', '', 'C'], ['157', '1', '3', '"Gilnagh', ' Miss. Katherine ""Katie"""', 'female', '16', '0', '0', '35851', '7.7333', '', 'Q'], ['158', '0', '3', '"Corn', ' Mr. Harry"', 'male', '30', '0', '0', 'SOTON/OQ 392090', '8.05', '', 'S'], ['159', '0', '3', '"Smiljanic', ' Mr. Mile"', 'male', '', '0', '0', '315037', '8.6625', '', 'S'], ['160', '0', '3', '"Sage', ' Master. Thomas Henry"', 'male', '', '8', '2', 'CA. 2343', '69.55', '', 'S'], ['161', '0', '3', '"Cribb', ' Mr. John Hatfield"', 'male', '44', '0', '1', '371362', '16.1', '', 'S'], ['162', '1', '2', '"Watt', ' Mrs. James (Elizabeth ""Bessie"" Inglis Milne)"', 'female', '40', '0', '0', 'C.A. 33595', '15.75', '', 'S'], ['163', '0', '3', '"Bengtsson', ' Mr. John Viktor"', 'male', '26', '0', '0', '347068', '7.775', '', 'S'], ['164', '0', '3', '"Calic', ' Mr. Jovo"', 'male', '17', '0', '0', '315093', '8.6625', '', 'S'], ['165', '0', '3', '"Panula', ' Master. Eino Viljami"', 'male', '1', '4', '1', '3101295', '39.6875', '', 'S'], ['166', '1', '3', '"Goldsmith', ' Master. Frank John William ""Frankie"""', 'male', '9', '0', '2', '363291', '20.525', '', 'S'], ['167', '1', '1', '"Chibnall', ' Mrs. (Edith Martha Bowerman)"', 'female', '', '0', '1', '113505', '55', 'E33', 'S'], ['168', '0', '3', '"Skoog', ' Mrs. William (Anna Bernhardina Karlsson)"', 'female', '45', '1', '4', '347088', '27.9', '', 'S'], ['169', '0', '1', '"Baumann', ' Mr. John D"', 'male', '', '0', '0', 'PC 17318', '25.925', '', 'S'], ['170', '0', '3', '"Ling', ' Mr. Lee"', 'male', '28', '0', '0', '1601', '56.4958', '', 'S'], ['171', '0', '1', '"Van der hoef', ' Mr. Wyckoff"', 'male', '61', '0', '0', '111240', '33.5', 'B19', 'S'], ['172', '0', '3', '"Rice', ' Master. Arthur"', 'male', '4', '4', '1', '382652', '29.125', '', 'Q'], ['173', '1', '3', '"Johnson', ' Miss. Eleanor Ileen"', 'female', '1', '1', '1', '347742', '11.1333', '', 'S'], ['174', '0', '3', '"Sivola', ' Mr. Antti Wilhelm"', 'male', '21', '0', '0', 'STON/O 2. 3101280', '7.925', '', 'S'], ['175', '0', '1', '"Smith', ' Mr. James Clinch"', 'male', '56', '0', '0', '17764', '30.6958', 'A7', 'C'], ['176', '0', '3', '"Klasen', ' Mr. Klas Albin"', 'male', '18', '1', '1', '350404', '7.8542', '', 'S'], ['177', '0', '3', '"Lefebre', ' Master. Henry Forbes"', 'male', '', '3', '1', '4133', '25.4667', '', 'S'], ['178', '0', '1', '"Isham', ' Miss. Ann Elizabeth"', 'female', '50', '0', '0', 'PC 17595', '28.7125', 'C49', 'C'], ['179', '0', '2', '"Hale', ' Mr. Reginald"', 'male', '30', '0', '0', '250653', '13', '', 'S'], ['180', '0', '3', '"Leonard', ' Mr. Lionel"', 'male', '36', '0', '0', 'LINE', '0', '', 'S'], ['181', '0', '3', '"Sage', ' Miss. Constance Gladys"', 'female', '', '8', '2', 'CA. 2343', '69.55', '', 'S'], ['182', '0', '2', '"Pernot', ' Mr. Rene"', 'male', '', '0', '0', 'SC/PARIS 2131', '15.05', '', 'C'], ['183', '0', '3', '"Asplund', ' Master. Clarence Gustaf Hugo"', 'male', '9', '4', '2', '347077', '31.3875', '', 'S'], ['184', 

In [11]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"""Braund","Mr. Owen Harris""",male,22,1,0,A/5 21171,7.25,
1,2,1,1,"""Cumings","Mrs. John Bradley (Florence Briggs Thayer)""",female,38,1,0,PC 17599,71.2833,C85
2,3,1,3,"""Heikkinen","Miss. Laina""",female,26,0,0,STON/O2. 3101282,7.925,
3,4,1,1,"""Futrelle","Mrs. Jacques Heath (Lily May Peel)""",female,35,1,0,113803,53.1,C123
4,5,0,3,"""Allen","Mr. William Henry""",male,35,0,0,373450,8.05,
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"""Montvila","Rev. Juozas""",male,27,0,0,211536,13,
887,888,1,1,"""Graham","Miss. Margaret Edith""",female,19,0,0,112053,30,B42
888,889,0,3,"""Johnston","Miss. Catherine Helen """"Carrie""""""",female,,1,2,W./C. 6607,23.45,
889,890,1,1,"""Behr","Mr. Karl Howell""",male,26,0,0,111369,30,C148
890,891,0,3,"""Dooley","Mr. Patrick""",male,32,0,0,370376,7.75,

In [17]:
# Method 1: Find rows with different column counts BEFORE converting to DataFrame
column_counts = [len(row) for row in parsed_data]
print("Column counts per row:")
print(f"Min columns: {min(column_counts)}, Max columns: {max(column_counts)}")

# Find rows that don't have 12 columns (or whatever standard count you want)
problematic_rows = [(i, len(row), row) for i, row in enumerate(parsed_data) if len(row) != 12]
print(len(problematic_rows))  # This will give you the number of rows that don't have 12 columns

print(f"\nRows with different column count (not 12):")
for row_idx, col_count, row_data in problematic_rows: # show all problematic rows which has different column count Basically more than 12 only   
    print(f"Row {row_idx}: has {col_count} columns - {row_data}")

Column counts per row:
Min columns: 12, Max columns: 13
891

Rows with different column count (not 12):
Row 1: has 13 columns - ['1', '0', '3', '"Braund', ' Mr. Owen Harris"', 'male', '22', '1', '0', 'A/5 21171', '7.25', '', 'S']
Row 2: has 13 columns - ['2', '1', '1', '"Cumings', ' Mrs. John Bradley (Florence Briggs Thayer)"', 'female', '38', '1', '0', 'PC 17599', '71.2833', 'C85', 'C']
Row 3: has 13 columns - ['3', '1', '3', '"Heikkinen', ' Miss. Laina"', 'female', '26', '0', '0', 'STON/O2. 3101282', '7.925', '', 'S']
Row 4: has 13 columns - ['4', '1', '1', '"Futrelle', ' Mrs. Jacques Heath (Lily May Peel)"', 'female', '35', '1', '0', '113803', '53.1', 'C123', 'S']
Row 5: has 13 columns - ['5', '0', '3', '"Allen', ' Mr. William Henry"', 'male', '35', '0', '0', '373450', '8.05', '', 'S']
Row 6: has 13 columns - ['6', '0', '3', '"Moran', ' Mr. James"', 'male', '', '0', '0', '330877', '8.4583', '', 'Q']
Row 7: has 13 columns - ['7', '0', '1', '"McCarthy', ' Mr. Timothy J"', 'male', '54', '0', '0', '17463', '51.8625', 'E46', 'S']
Row 8: has 13 columns - ['8', '0', '3', '"Palsson', ' Master. Gosta Leonard"', 'male', '2', '3', '1', '349909', '21.075', '', 'S']
Row 9: has 13 columns - ['9', '1', '3', '"Johnson', ' Mrs. Oscar W (Elisabeth Vilhelmina Berg)"', 'female', '27', '0', '2', '347742', '11.1333', '', 'S']
Row 10: has 13 columns - ['10', '1', '2', '"Nasser', ' Mrs. Nicholas (Adele Achem)"', 'female', '14', '1', '0', '237736', '30.0708', '', 'C']
Row 11: has 13 columns - ['11', '1', '3', '"Sandstrom', ' Miss. Marguerite Rut"', 'female', '4', '1', '1', 'PP 9549', '16.7', 'G6', 'S']
Row 12: has 13 columns - ['12', '1', '1', '"Bonnell', ' Miss. Elizabeth"', 'female', '58', '0', '0', '113783', '26.55', 'C103', 'S']
Row 13: has 13 columns - ['13', '0', '3', '"Saundercock', ' Mr. William Henry"', 'male', '20', '0', '0', 'A/5. 2151', '8.05', '', 'S']
Row 14: has 13 columns - ['14', '0', '3', '"Andersson', ' Mr. Anders Johan"', 'male', '39', '1', '5', '347082', '31.275', '', 'S']
Row 15: has 13 columns - ['15', '0', '3', '"Vestrom', ' Miss. Hulda Amanda Adolfina"', 'female', '14', '0', '0', '350406', '7.8542', '', 'S']
Row 16: has 13 columns - ['16', '1', '2', '"Hewlett', ' Mrs. (Mary D Kingcome) "', 'female', '55', '0', '0', '248706', '16', '', 'S']
Row 17: has 13 columns - ['17', '0', '3', '"Rice', ' Master. Eugene"', 'male', '2', '4', '1', '382652', '29.125', '', 'Q']
Row 18: has 13 columns - ['18', '1', '2', '"Williams', ' Mr. Charles Eugene"', 'male', '', '0', '0', '244373', '13', '', 'S']
Row 19: has 13 columns - ['19', '0', '3', '"Vander Planke', ' Mrs. Julius (Emelia Maria Vandemoortele)"', 'female', '31', '1', '0', '345763', '18', '', 'S']
Row 20: has 13 columns - ['20', '1', '3', '"Masselmani', ' Mrs. Fatima"', 'female', '', '0', '0', '2649', '7.225', '', 'C']
Row 21: has 13 columns - ['21', '0', '2', '"Fynney', ' Mr. Joseph J"', 'male', '35', '0', '0', '239865', '26', '', 'S']
Row 22: has 13 columns - ['22', '1', '2', '"Beesley', ' Mr. Lawrence"', 'male', '34', '0', '0', '248698', '13', 'D56', 'S']
Row 23: has 13 columns - ['23', '1', '3', '"McGowan', ' Miss. Anna ""Annie"""', 'female', '15', '0', '0', '330923', '8.0292', '', 'Q']
Row 24: has 13 columns - ['24', '1', '1', '"Sloper', ' Mr. William Thompson"', 'male', '28', '0', '0', '113788', '35.5', 'A6', 'S']
Row 25: has 13 columns - ['25', '0', '3', '"Palsson', ' Miss. Torborg Danira"', 'female', '8', '3', '1', '349909', '21.075', '', 'S']
Row 26: has 13 columns - ['26', '1', '3', '"Asplund', ' Mrs. Carl Oscar (Selma Augusta Emilia Johansson)"', 'female', '38', '1', '5', '347077', '31.3875', '', 'S']
Row 27: has 13 columns - ['27', '0', '3', '"Emir', ' Mr. Farred Chehab"', 'male', '', '0', '0', '2631', '7.225', '', 'C']
Row 28: has 13 columns - ['28', '0', '1', '"Fortune', ' Mr. Charles Alexander"', 'male', '19', '3', '2', '19950', '263', 'C23 C25 C27', 'S']
Row 29: has 13 columns - ['29', '1', '3', '"O\'Dwyer', ' Miss. Ellen ""Nellie"""', 'female', '', '0', '0', '330959', '7.8792', '', 'Q']
Row 30: has 13 columns - ['30', '0', '3', '"Todoroff', ' Mr. Lalio"', 'male', '', '0', '0', '349216', '7.8958', '', 'S']
Row 31: has 13 columns - ['31', '0', '1', '"Uruchurtu', ' Don. Manuel E"', 'male', '40', '0', '0', 'PC 17601', '27.7208', '', 'C']
Row 32: has 13 columns - ['32', '1', '1', '"Spencer', ' Mrs. William Augustus (Marie Eugenie)"', 'female', '', '1', '0', 'PC 17569', '146.5208', 'B78', 'C']
Row 33: has 13 columns - ['33', '1', '3', '"Glynn', ' Miss. Mary Agatha"', 'female', '', '0', '0', '335677', '7.75', '', 'Q']
Row 34: has 13 columns - ['34', '0', '2', '"Wheadon', ' Mr. Edward H"', 'male', '66', '0', '0', 'C.A. 24579', '10.5', '', 'S']
Row 35: has 13 columns - ['35', '0', '1', '"Meyer', ' Mr. Edgar Joseph"', 'male', '28', '1', '0', 'PC 17604', '82.1708', '', 'C']
Row 36: has 13 columns - ['36', '0', '1', '"Holverson', ' Mr. Alexander Oskar"', 'male', '42', '1', '0', '113789', '52', '', 'S']
Row 37: has 13 columns - ['37', '1', '3', '"Mamee', ' Mr. Hanna"', 'male', '', '0', '0', '2677', '7.2292', '', 'C']
Row 38: has 13 columns - ['38', '0', '3', '"Cann', ' Mr. Ernest Charles"', 'male', '21', '0', '0', 'A./5. 2152', '8.05', '', 'S']
Row 39: has 13 columns - ['39', '0', '3', '"Vander Planke', ' Miss. Augusta Maria"', 'female', '18', '2', '0', '345764', '18', '', 'S']
Row 40: has 13 columns - ['40', '1', '3', '"Nicola-Yarred', ' Miss. Jamila"', 'female', '14', '1', '0', '2651', '11.2417', '', 'C']
Row 41: has 13 columns - ['41', '0', '3', '"Ahlin', ' Mrs. Johan (Johanna Persdotter Larsson)"', 'female', '40', '1', '0', '7546', '9.475', '', 'S']
Row 42: has 13 columns - ['42', '0', '2', '"Turpin', ' Mrs. William John Robert (Dorothy Ann Wonnacott)"', 'female', '27', '1', '0', '11668', '21', '', 'S']
Row 43: has 13 columns - ['43', '0', '3', '"Kraeff', ' Mr. Theodor"', 'male', '', '0', '0', '349253', '7.8958', '', 'C']
Row 44: has 13 columns - ['44', '1', '2', '"Laroche', ' Miss. Simonne Marie Anne Andree"', 'female', '3', '1', '2', 'SC/Paris 2123', '41.5792', '', 'C']
Row 45: has 13 columns - ['45', '1', '3', '"Devaney', ' Miss. Margaret Delia"', 'female', '19', '0', '0', '330958', '7.8792', '', 'Q']
Row 46: has 13 columns - ['46', '0', '3', '"Rogers', ' Mr. William John"', 'male', '', '0', '0', 'S.C./A.4. 23567', '8.05', '', 'S']
Row 47: has 13 columns - ['47', '0', '3', '"Lennon', ' Mr. Denis"', 'male', '', '1', '0', '370371', '15.5', '', 'Q']
Row 48: has 13 columns - ['48', '1', '3', '"O\'Driscoll', ' Miss. Bridget"', 'female', '', '0', '0', '14311', '7.75', '', 'Q']
Row 49: has 13 columns - ['49', '0', '3', '"Samaan', ' Mr. Youssef"', 'male', '', '2', '0', '2662', '21.6792', '', 'C']
Row 50: has 13 columns - ['50', '0', '3', '"Arnold-Franchi', ' Mrs. Josef (Josefine Franchi)"', 'female', '18', '1', '0', '349237', '17.8', '', 'S']
Row 51: has 13 columns - ['51', '0', '3', '"Panula', ' Master. Juha Niilo"', 'male', '7', '4', '1', '3101295', '39.6875', '', 'S']
Row 52: has 13 columns - ['52', '0', '3', '"Nosworthy', ' Mr. Richard Cater"', 'male', '21', '0', '0', 'A/4. 39886', '7.8', '', 'S']
Row 53: has 13 columns - ['53', '1', '1', '"Harper', ' Mrs. Henry Sleeper (Myna Haxtun)"', 'female', '49', '1', '0', 'PC 17572', '76.7292', 'D33', 'C']
Row 54: has 13 columns - ['54', '1', '2', '"Faunthorpe', ' Mrs. Lizzie (Elizabeth Anne Wilkinson)"', 'female', '29', '1', '0', '2926', '26', '', 'S']
Row 55: has 13 columns - ['55', '0', '1', '"Ostby', ' Mr. Engelhart Cornelius"', 'male', '65', '0', '1', '113509', '61.9792', 'B30', 'C']
Row 56: has 13 columns - ['56', '1', '1', '"Woolner', ' Mr. Hugh"', 'male', '', '0', '0', '19947', '35.5', 'C52', 'S']
Row 57: has 13 columns - ['57', '1', '2', '"Rugg', ' Miss. Emily"', 'female', '21', '0', '0', 'C.A. 31026', '10.5', '', 'S']
Row 58: has 13 columns - ['58', '0', '3', '"Novel', ' Mr. Mansouer"', 'male', '28.5', '0', '0', '2697', '7.2292', '', 'C']
Row 59: has 13 columns - ['59', '1', '2', '"West', ' Miss. Constance Mirium"', 'female', '5', '1', '2', 'C.A. 34651', '27.75', '', 'S']
Row 60: has 13 columns - ['60', '0', '3', '"Goodwin', ' Master. William Frederick"', 'male', '11', '5', '2', 'CA 2144', '46.9', '', 'S']
Row 61: has 13 columns - ['61', '0', '3', '"Sirayanian', ' Mr. Orsen"', 'male', '22', '0', '0', '2669', '7.2292', '', 'C']
Row 62: has 13 columns - ['62', '1', '1', '"Icard', ' Miss. Amelie"', 'female', '38', '0', '0', '113572', '80', 'B28', '']
Row 63: has 13 columns - ['63', '0', '1', '"Harris', ' Mr. Henry Birkhardt"', 'male', '45', '1', '0', '36973', '83.475', 'C83', 'S']
Row 64: has 13 columns - ['64', '0', '3', '"Skoog', ' Master. Harald"', 'male', '4', '3', '2', '347088', '27.9', '', 'S']
Row 65: has 13 columns - ['65', '0', '1', '"Stewart', ' Mr. Albert A"', 'male', '', '0', '0', 'PC 17605', '27.7208', '', 'C']
Row 66: has 13 columns - ['66', '1', '3', '"Moubarek', ' Master. Gerios"', 'male', '', '1', '1', '2661', '15.2458', '', 'C']
Row 67: has 13 columns - ['67', '1', '2', '"Nye', ' Mrs. (Elizabeth Ramell)"', 'female', '29', '0', '0', 'C.A. 29395', '10.5', 'F33', 'S']
Row 68: has 13 columns - ['68', '0', '3', '"Crease', ' Mr. Ernest James"', 'male', '19', '0', '0', 'S.P. 3464', '8.1583', '', 'S']
Row 69: has 13 columns - ['69', '1', '3', '"Andersson', ' Miss. Erna Alexandra"', 'female', '17', '4', '2', '3101281', '7.925', '', 'S']
Row 70: has 13 columns - ['70', '0', '3', '"Kink', ' Mr. Vincenz"', 'male', '26', '2', '0', '315151', '8.6625', '', 'S']
Row 71: has 13 columns - ['71', '0', '2', '"Jenkin', ' Mr. Stephen Curnow"', 'male', '32', '0', '0', 'C.A. 33111', '10.5', '', 'S']
Row 72: has 13 columns - ['72', '0', '3', '"Goodwin', ' Miss. Lillian Amy"', 'female', '16', '5', '2', 'CA 2144', '46.9', '', 'S']
Row 73: has 13 columns - ['73', '0', '2', '"Hood', ' Mr. Ambrose Jr"', 'male', '21', '0', '0', 'S.O.C. 14879', '73.5', '', 'S']
Row 74: has 13 columns - ['74', '0', '3', '"Chronopoulos', ' Mr. Apostolos"', 'male', '26', '1', '0', '2680', '14.4542', '', 'C']
Row 75: has 13 columns - ['75', '1', '3', '"Bing', ' Mr. Lee"', 'male', '32', '0', '0', '1601', '56.4958', '', 'S']
Row 76: has 13 columns - ['76', '0', '3', '"Moen', ' Mr. Sigurd Hansen"', 'male', '25', '0', '0', '348123', '7.65', 'F G73', 'S']
Row 77: has 13 columns - ['77', '0', '3', '"Staneff', ' Mr. Ivan"', 'male', '', '0', '0', '349208', '7.8958', '', 'S']
Row 78: has 13 columns - ['78', '0', '3', '"Moutal', ' Mr. Rahamin Haim"', 'male', '', '0', '0', '374746', '8.05', '', 'S']
Row 79: has 13 columns - ['79', '1', '2', '"Caldwell', ' Master. Alden Gates"', 'male', '0.83', '0', '2', '248738', '29', '', 'S']
Row 80: has 13 columns - ['80', '1', '3', '"Dowdell', ' Miss. Elizabeth"', 'female', '30', '0', '0', '364516', '12.475', '', 'S']
Row 81: has 13 columns - ['81', '0', '3', '"Waelens', ' Mr. Achille"', 'male', '22', '0', '0', '345767', '9', '', 'S']
Row 82: has 13 columns - ['82', '1', '3', '"Sheerlinck', ' Mr. Jan Baptist"', 'male', '29', '0', '0', '345779', '9.5', '', 'S']
Row 83: has 13 columns - ['83', '1', '3', '"McDermott', ' Miss. Brigdet Delia"', 'female', '', '0', '0', '330932', '7.7875', '', 'Q']
Row 84: has 13 columns - ['84', '0', '1', '"Carrau', ' Mr. Francisco M"', 'male', '28', '0', '0', '113059', '47.1', '', 'S']
Row 85: has 13 columns - ['85', '1', '2', '"Ilett', ' Miss. Bertha"', 'female', '17', '0', '0', 'SO/C 14885', '10.5', '', 'S']
Row 86: has 13 columns - ['86', '1', '3', '"Backstrom', ' Mrs. Karl Alfred (Maria Mathilda Gustafsson)"', 'female', '33', '3', '0', '3101278', '15.85', '', 'S']
Row 87: has 13 columns - ['87', '0', '3', '"Ford', ' Mr. William Neal"', 'male', '16', '1', '3', 'W./C. 6608', '34.375', '', 'S']
Row 88: has 13 columns - ['88', '0', '3', '"Slocovski', ' Mr. Selman Francis"', 'male', '', '0', '0', 'SOTON/OQ 392086', '8.05', '', 'S']
Row 89: has 13 columns - ['89', '1', '1', '"Fortune', ' Miss. Mabel Helen"', 'female', '23', '3', '2', '19950', '263', 'C23 C25 C27', 'S']
Row 90: has 13 columns - ['90', '0', '3', '"Celotti', ' Mr. Francesco"', 'male', '24', '0', '0', '343275', '8.05', '', 'S']
Row 91: has 13 columns - ['91', '0', '3', '"Christmann', ' Mr. Emil"', 'male', '29', '0', '0', '343276', '8.05', '', 'S']
Row 92: has 13 columns - ['92', '0', '3', '"Andreasson', ' Mr. Paul Edvin"', 'male', '20', '0', '0', '347466', '7.8542', '', 'S']
Row 93: has 13 columns - ['93', '0', '1', '"Chaffee', ' Mr. Herbert Fuller"', 'male', '46', '1', '0', 'W.E.P. 5734', '61.175', 'E31', 'S']
Row 94: has 13 columns - ['94', '0', '3', '"Dean', ' Mr. Bertram Frank"', 'male', '26', '1', '2', 'C.A. 2315', '20.575', '', 'S']
Row 95: has 13 columns - ['95', '0', '3', '"Coxon', ' Mr. Daniel"', 'male', '59', '0', '0', '364500', '7.25', '', 'S']
Row 96: has 13 columns - ['96', '0', '3', '"Shorney', ' Mr. Charles Joseph"', 'male', '', '0', '0', '374910', '8.05', '', 'S']
Row 97: has 13 columns - ['97', '0', '1', '"Goldschmidt', ' Mr. George B"', 'male', '71', '0', '0', 'PC 17754', '34.6542', 'A5', 'C']
Row 98: has 13 columns - ['98', '1', '1', '"Greenfield', ' Mr. William Bertram"', 'male', '23', '0', '1', 'PC 17759', '63.3583', 'D10 D12', 'C']
Row 99: has 13 columns - ['99', '1', '2', '"Doling', ' Mrs. John T (Ada Julia Bone)"', 'female', '34', '0', '1', '231919', '23', '', 'S']
Row 100: has 13 columns - ['100', '0', '2', '"Kantor', ' Mr. Sinai"', 'male', '34', '1', '0', '244367', '26', '', 'S']
Row 101: has 13 columns - ['101', '0', '3', '"Petranec', ' Miss. Matilda"', 'female', '28', '0', '0', '349245', '7.8958', '', 'S']
Row 102: has 13 columns - ['102', '0', '3', '"Petroff', ' Mr. Pastcho (""Pentcho"")"', 'male', '', '0', '0', '349215', '7.8958', '', 'S']
Row 103: has 13 columns - ['103', '0', '1', '"White', ' Mr. Richard Frasar"', 'male', '21', '0', '1', '35281', '77.2875', 'D26', 'S']
Row 104: has 13 columns - ['104', '0', '3', '"Johansson', ' Mr. Gustaf Joel"', 'male', '33', '0', '0', '7540', '8.6542', '', 'S']
Row 105: has 13 columns - ['105', '0', '3', '"Gustafsson', ' Mr. Anders Vilhelm"', 'male', '37', '2', '0', '3101276', '7.925', '', 'S']
Row 106: has 13 columns - ['106', '0', '3', '"Mionoff', ' Mr. Stoytcho"', 'male', '28', '0', '0', '349207', '7.8958', '', 'S']
Row 107: has 13 columns - ['107', '1', '3', '"Salkjelsvik', ' Miss. Anna Kristine"', 'female', '21', '0', '0', '343120', '7.65', '', 'S']
Row 108: has 13 columns - ['108', '1', '3', '"Moss', ' Mr. Albert Johan"', 'male', '', '0', '0', '312991', '7.775', '', 'S']
Row 109: has 13 columns - ['109', '0', '3', '"Rekic', ' Mr. Tido"', 'male', '38', '0', '0', '349249', '7.8958', '', 'S']
Row 110: has 13 columns - ['110', '1', '3', '"Moran', ' Miss. Bertha"', 'female', '', '1', '0', '371110', '24.15', '', 'Q']
Row 111: has 13 columns - ['111', '0', '1', '"Porter', ' Mr. Walter Chamberlain"', 'male', '47', '0', '0', '110465', '52', 'C110', 'S']
Row 112: has 13 columns - ['112', '0', '3', '"Zabour', ' Miss. Hileni"', 'female', '14.5', '1', '0', '2665', '14.4542', '', 'C']
Row 113: has 13 columns - ['113', '0', '3', '"Barton', ' Mr. David John"', 'male', '22', '0', '0', '324669', '8.05', '', 'S']
Row 114: has 13 columns - ['114', '0', '3', '"Jussila', ' Miss. Katriina"', 'female', '20', '1', '0', '4136', '9.825', '', 'S']
Row 115: has 13 columns - ['115', '0', '3', '"Attalah', ' Miss. Malake"', 'female', '17', '0', '0', '2627', '14.4583', '', 'C']
Row 116: has 13 columns - ['116', '0', '3', '"Pekoniemi', ' Mr. Edvard"', 'male', '21', '0', '0', 'STON/O 2. 3101294', '7.925', '', 'S']
Row 117: has 13 columns - ['117', '0', '3', '"Connors', ' Mr. Patrick"', 'male', '70.5', '0', '0', '370369', '7.75', '', 'Q']
Row 118: has 13 columns - ['118', '0', '2', '"Turpin', ' Mr. William John Robert"', 'male', '29', '1', '0', '11668', '21', '', 'S']
Row 119: has 13 columns - ['119', '0', '1', '"Baxter', ' Mr. Quigg Edmond"', 'male', '24', '0', '1', 'PC 17558', '247.5208', 'B58 B60', 'C']
Row 120: has 13 columns - ['120', '0', '3', '"Andersson', ' Miss. Ellis Anna Maria"', 'female', '2', '4', '2', '347082', '31.275', '', 'S']
Row 121: has 13 columns - ['121', '0', '2', '"Hickman', ' Mr. Stanley George"', 'male', '21', '2', '0', 'S.O.C. 14879', '73.5', '', 'S']
Row 122: has 13 columns - ['122', '0', '3', '"Moore', ' Mr. Leonard Charles"', 'male', '', '0', '0', 'A4. 54510', '8.05', '', 'S']
Row 123: has 13 columns - ['123', '0', '2', '"Nasser', ' Mr. Nicholas"', 'male', '32.5', '1', '0', '237736', '30.0708', '', 'C']
Row 124: has 13 columns - ['124', '1', '2', '"Webber', ' Miss. Susan"', 'female', '32.5', '0', '0', '27267', '13', 'E101', 'S']
Row 125: has 13 columns - ['125', '0', '1', '"White', ' Mr. Percival Wayland"', 'male', '54', '0', '1', '35281', '77.2875', 'D26', 'S']
Row 126: has 13 columns - ['126', '1', '3', '"Nicola-Yarred', ' Master. Elias"', 'male', '12', '1', '0', '2651', '11.2417', '', 'C']
Row 127: has 13 columns - ['127', '0', '3', '"McMahon', ' Mr. Martin"', 'male', '', '0', '0', '370372', '7.75', '', 'Q']
Row 128: has 13 columns - ['128', '1', '3', '"Madsen', ' Mr. Fridtjof Arne"', 'male', '24', '0', '0', 'C 17369', '7.1417', '', 'S']
Row 129: has 13 columns - ['129', '1', '3', '"Peter', ' Miss. Anna"', 'female', '', '1', '1', '2668', '22.3583', 'F E69', 'C']
Row 130: has 13 columns - ['130', '0', '3', '"Ekstrom', ' Mr. Johan"', 'male', '45', '0', '0', '347061', '6.975', '', 'S']
Row 131: has 13 columns - ['131', '0', '3', '"Drazenoic', ' Mr. Jozef"', 'male', '33', '0', '0', '349241', '7.8958', '', 'C']
Row 132: has 13 columns - ['132', '0', '3', '"Coelho', ' Mr. Domingos Fernandeo"', 'male', '20', '0', '0', 'SOTON/O.Q. 3101307', '7.05', '', 'S']
Row 133: has 13 columns - ['133', '0', '3', '"Robins', ' Mrs. Alexander A (Grace Charity Laury)"', 'female', '47', '1', '0', 'A/5. 3337', '14.5', '', 'S']
Row 134: has 13 columns - ['134', '1', '2', '"Weisz', ' Mrs. Leopold (Mathilde Francoise Pede)"', 'female', '29', '1', '0', '228414', '26', '', 'S']
Row 135: has 13 columns - ['135', '0', '2', '"Sobey', ' Mr. Samuel James Hayden"', 'male', '25', '0', '0', 'C.A. 29178', '13', '', 'S']
Row 136: has 13 columns - ['136', '0', '2', '"Richard', ' Mr. Emile"', 'male', '23', '0', '0', 'SC/PARIS 2133', '15.0458', '', 'C']
Row 137: has 13 columns - ['137', '1', '1', '"Newsom', ' Miss. Helen Monypeny"', 'female', '19', '0', '2', '11752', '26.2833', 'D47', 'S']
Row 138: has 13 columns - ['138', '0', '1', '"Futrelle', ' Mr. Jacques Heath"', 'male', '37', '1', '0', '113803', '53.1', 'C123', 'S']
Row 139: has 13 columns - ['139', '0', '3', '"Osen', ' Mr. Olaf Elon"', 'male', '16', '0', '0', '7534', '9.2167', '', 'S']
Row 140: has 13 columns - ['140', '0', '1', '"Giglio', ' Mr. Victor"', 'male', '24', '0', '0', 'PC 17593', '79.2', 'B86', 'C']
Row 141: has 13 columns - ['141', '0', '3', '"Boulos', ' Mrs. Joseph (Sultana)"', 'female', '', '0', '2', '2678', '15.2458', '', 'C']
Row 142: has 13 columns - ['142', '1', '3', '"Nysten', ' Miss. Anna Sofia"', 'female', '22', '0', '0', '347081', '7.75', '', 'S']
Row 143: has 13 columns - ['143', '1', '3', '"Hakkarainen', ' Mrs. Pekka Pietari (Elin Matilda Dolck)"', 'female', '24', '1', '0', 'STON/O2. 3101279', '15.85', '', 'S']
Row 144: has 13 columns - ['144', '0', '3', '"Burke', ' Mr. Jeremiah"', 'male', '19', '0', '0', '365222', '6.75', '', 'Q']
Row 145: has 13 columns - ['145', '0', '2', '"Andrew', ' Mr. Edgardo Samuel"', 'male', '18', '0', '0', '231945', '11.5', '', 'S']
Row 146: has 13 columns - ['146', '0', '2', '"Nicholls', ' Mr. Joseph Charles"', 'male', '19', '1', '1', 'C.A. 33112', '36.75', '', 'S']
Row 147: has 13 columns - ['147', '1', '3', '"Andersson', ' Mr. August Edvard (""Wennerstrom"")"', 'male', '27', '0', '0', '350043', '7.7958', '', 'S']
Row 148: has 13 columns - ['148', '0', '3', '"Ford', ' Miss. Robina Maggie ""Ruby"""', 'female', '9', '2', '2', 'W./C. 6608', '34.375', '', 'S']
Row 149: has 13 columns - ['149', '0', '2', '"Navratil', ' Mr. Michel (""Louis M Hoffman"")"', 'male', '36.5', '0', '2', '230080', '26', 'F2', 'S']

In [18]:
from io import StringIO
df = pd.read_csv(StringIO(response.text), on_bad_lines='warn')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [20]:
# Skip rows with wrong number of columns
df = pd.read_csv(StringIO(response.text), on_bad_lines='skip')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

*rapidapi.com* open source platform for access data

In [21]:
from io import StringIO

# Clean DataFrame in one line - skips rows with wrong column count
df_clean = pd.read_csv(StringIO(response.text), on_bad_lines='skip')

# Verify it's clean
print(f"Shape: {df_clean.shape}")
print(df_clean.info())
df_clean.head()

Shape: (891, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

========================================
📊 DATA CLEANING SUMMARY
========================================
Rows BEFORE cleaning: 891
Rows AFTER cleaning:  891
Rows removed:         0
Percentage removed:   0.00%
========================================